version: "3.8"

services:
  jenkins-blueocean:
    image: jenkins-docker
    container_name: jenkins
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=0
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:rw
      - //var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:
